# ============================================================
# 02_load_expression_data.R
# GitHub-ready version: project-relative paths
# ============================================================
# Large source files belong in data_raw/ and are intentionally
# excluded from Git. The reduced VCM matrix is generated locally.
# See data_raw/README.md.
# ============================================================

# ============================================================
# Project: Healthy female human heart aging analysis
# Script 02: Prepare for loading the snRNA-seq expression data
#
# Dataset:
# Read et al. 2024 human heart snRNA-seq meta-analysis
#
# Purpose of this script:
# 1. Load packages needed for downstream single-cell analysis
# 2. Load the final female LV cohort generated in Script 01
# 3. Verify that the cohort was imported correctly
# 4. Confirm the younger and older donor numbers
# 5. Store the 24 donor IDs that will be matched to the
#    single-nucleus expression dataset
#
# NOTE:
# We are NOT loading the large expression dataset yet.
# First, we confirm that the donor cohort is correct.
# ============================================================


# ------------------------------------------------------------
# STEP 1: Install required packages
# ------------------------------------------------------------
# These commands only need to be run ONCE.
#
# If the packages are already installed, leave these lines
# commented out.
#
# BiocManager is used to install Bioconductor packages.

# install.packages("BiocManager")

# BiocManager::install(c(
#   "SingleCellExperiment",
#   "scuttle",
#   "edgeR"
# ))


# ------------------------------------------------------------
# STEP 2: Load required packages
# ------------------------------------------------------------
#
# SingleCellExperiment:
# Standard Bioconductor structure for single-cell datasets.
#
# scuttle:
# Functions for manipulating and aggregating single-cell data.
#
# edgeR:
# Will later be used for donor-level pseudobulk differential
# expression analysis.
#
# tidyverse is loaded LAST here so that common data-manipulation
# functions from dplyr are available after Bioconductor packages
# have been attached.

library(SingleCellExperiment)
library(scuttle)
library(edgeR)

library(tidyverse)


# ------------------------------------------------------------
# STEP 3: Confirm the current project directory
# ------------------------------------------------------------
# This tells us where R is currently looking for files.
#
# It should point to your:
# repository root

getwd()


# ------------------------------------------------------------
# STEP 4: Create a folder for expression data
# ------------------------------------------------------------
# The large processed snRNA-seq object will eventually be
# placed inside this folder.

dir.create(
  "data",
  showWarnings = FALSE
)


# ------------------------------------------------------------
# STEP 5: Confirm that the cohort file from Script 01 exists
# ------------------------------------------------------------
# This should return TRUE.

file.exists(
  "results/tables/female_LV_primary_cohort.csv"
)


# ------------------------------------------------------------
# STEP 6: Load the final female LV cohort
# ------------------------------------------------------------
# This file was generated by Script 01.
#
# We load it again rather than relying on the object currently
# sitting in the RStudio Environment.
#
# This makes Script 02 independently reproducible.

female_lv <- readr::read_csv(
  "results/tables/female_LV_primary_cohort.csv",
  show_col_types = FALSE
)


# ------------------------------------------------------------
# STEP 7: Inspect the imported object
# ------------------------------------------------------------
# Confirm that female_lv is a data frame/tibble and examine
# the structure of each column.

class(female_lv)

dim(female_lv)

names(female_lv)

str(female_lv)


# ------------------------------------------------------------
# STEP 8: Inspect the first few donors
# ------------------------------------------------------------

head(female_lv)


# ------------------------------------------------------------
# STEP 9: Verify that age_group is a normal character column
# ------------------------------------------------------------
# We expect age_group to contain values such as:
#
# Younger_20_45
# Older_55plus

class(female_lv$age_group)

unique(female_lv$age_group)


# ------------------------------------------------------------
# STEP 10: Count donors in each age group
# ------------------------------------------------------------
# We explicitly use dplyr::count() because some Bioconductor
# packages can contain functions with the same name as functions
# in other packages.
#
# Using package::function guarantees that R uses the function
# we intend.

age_group_counts <- female_lv %>%
  dplyr::count(
    age_group,
    name = "n_donors"
  )

age_group_counts


# ------------------------------------------------------------
# STEP 11: Confirm total number of donors
# ------------------------------------------------------------
# We expect 24 total female donors with LV tissue.

nrow(female_lv)


# ------------------------------------------------------------
# STEP 12: Inspect the final donor cohort
# ------------------------------------------------------------
# Sort donors by age and display the variables most important
# for our analysis.

female_lv %>%
  dplyr::arrange(age) %>%
  dplyr::select(
    donor,
    age,
    age_group,
    data_source,
    sites_sampled
  )


# ------------------------------------------------------------
# STEP 13: Check study representation by age group
# ------------------------------------------------------------
# This is important because the younger and older donors are
# not distributed equally across the original studies.
#
# Study/data source may therefore act as a confounding factor
# and will need to be considered during differential expression.

study_age_counts <- female_lv %>%
  dplyr::count(
    data_source,
    age_group,
    name = "n_donors"
  )

study_age_counts


# ------------------------------------------------------------
# STEP 14: Display study representation as a wide table
# ------------------------------------------------------------
# This makes it easier to see which studies contain:
# - younger donors
# - older donors
# - both groups

study_age_table <- study_age_counts %>%
  tidyr::pivot_wider(
    names_from = age_group,
    values_from = n_donors,
    values_fill = 0
  )

study_age_table


# ------------------------------------------------------------
# STEP 15: Store the target donor IDs
# ------------------------------------------------------------
# These are the donor IDs that we will later match against
# the cell-level metadata in the snRNA-seq expression dataset.

target_donors <- female_lv$donor


# ------------------------------------------------------------
# STEP 16: Confirm the number of target donors
# ------------------------------------------------------------
# Expected result:
# [1] 24

length(target_donors)


# ------------------------------------------------------------
# STEP 17: Display all target donor IDs
# ------------------------------------------------------------

target_donors


# ------------------------------------------------------------
# STEP 18: Check for duplicate donor IDs
# ------------------------------------------------------------
# Each donor should appear once in this donor-level metadata
# table.
#
# Expected result:
# [1] 0

sum(
  duplicated(target_donors)
)


# ------------------------------------------------------------
# STEP 19: Check for missing donor IDs
# ------------------------------------------------------------
# We do not want NA donor IDs before trying to match these
# donors to the expression dataset.
#
# Expected result:
# [1] 0

sum(
  is.na(target_donors)
)


# ------------------------------------------------------------
# STEP 20: Check for missing ages or age groups
# ------------------------------------------------------------
# Expected results should both be 0.

sum(
  is.na(female_lv$age)
)

sum(
  is.na(female_lv$age_group)
)


# ------------------------------------------------------------
# STEP 21: Save the target donor IDs
# ------------------------------------------------------------
# This simple text file gives us a permanent record of the
# 24 donor IDs selected for the primary analysis.

readr::write_lines(
  target_donors,
  "results/tables/female_LV_donor_IDs.txt"
)


# ------------------------------------------------------------
# STEP 22: Save study-by-age-group sample counts
# ------------------------------------------------------------
# This table documents the study composition of our cohort
# and will be useful when designing the statistical model.

readr::write_csv(
  study_age_table,
  "results/tables/female_LV_study_age_counts.csv"
)


# ============================================================
# END OF SCRIPT 02 PREPARATION
#
# Expected key results:
#
# Total LV female donors = 24
#
# Younger_20_45 = 5 donors
# Older_55plus  = 19 donors
#
# Next step:
# Obtain and load the processed snRNA-seq expression dataset,
# inspect its cell-level metadata, and match these 24 donor IDs.
# ============================================================
# ------------------------------------------------------------
# STEP 23: Load the multi-study cell-level metadata
# ------------------------------------------------------------
# This file was downloaded from the authors' official
# processed-data repository.
#
# It contains metadata for each nucleus in the multi-study
# snRNA-seq dataset.

cell_meta <- readr::read_csv(
  file.path("data_raw", "multi_study_snRNA_Seq_cell_data.csv"),
  show_col_types = FALSE
)


# ------------------------------------------------------------
# STEP 24: Inspect the dimensions of the cell metadata
# ------------------------------------------------------------
# Rows = nuclei
# Columns = metadata variables

dim(cell_meta)


# ------------------------------------------------------------
# STEP 25: Inspect the column names
# ------------------------------------------------------------
# We need to identify the exact names used for:
# donor
# sex
# age
# data source
# anatomical site
# cell type

names(cell_meta)


# ------------------------------------------------------------
# STEP 26: Inspect the first few rows
# ------------------------------------------------------------

head(cell_meta)


# ------------------------------------------------------------
# STEP 27: Inspect the structure of the metadata
# ------------------------------------------------------------

str(cell_meta)


# ------------------------------------------------------------
# STEP 28: Search for likely donor-related columns
# ------------------------------------------------------------

names(cell_meta)[
  stringr::str_detect(
    names(cell_meta),
    regex(
      "donor|sample|patient|subject",
      ignore_case = TRUE
    )
  )
]


# ------------------------------------------------------------
# STEP 29: Search for likely cell-type columns
# ------------------------------------------------------------

names(cell_meta)[
  stringr::str_detect(
    names(cell_meta),
    regex(
      "cell|type|label|cluster",
      ignore_case = TRUE
    )
  )
]


# ------------------------------------------------------------
# STEP 30: Search for likely anatomy/site columns
# ------------------------------------------------------------

names(cell_meta)[
  stringr::str_detect(
    names(cell_meta),
    regex(
      "site|anatom|region|tissue",
      ignore_case = TRUE
    )
  )
]


# ------------------------------------------------------------
# STEP 31: Search for sex, age, and study columns
# ------------------------------------------------------------

names(cell_meta)[
  stringr::str_detect(
    names(cell_meta),
    regex(
      "sex|age|source|study",
      ignore_case = TRUE
    )
  )
]


#Now we need the exact 14 column names before writing the donor-matching/subsetting code
names(cell_meta)
# ------------------------------------------------------------
# STEP 32: Check how many of our 24 target donors are present
# ------------------------------------------------------------
# target_donors contains the 24 female LV donors selected
# from the donor-level metadata in Script 01.
#
# cell_meta contains one row per nucleus.
#
# Here we compare the donor IDs from both sources.

donor_match_table <- tibble(
  donor = target_donors,
  present_in_cell_meta = target_donors %in% unique(cell_meta$Donor)
)

donor_match_table


# ------------------------------------------------------------
# STEP 33: Count how many target donors were found
# ------------------------------------------------------------
# Expected result:
# ideally 24

sum(donor_match_table$present_in_cell_meta)


# ------------------------------------------------------------
# STEP 34: Identify any donor IDs that were NOT found
# ------------------------------------------------------------
# Ideally this should return character(0).

target_donors[
  !target_donors %in% unique(cell_meta$Donor)
]


# ------------------------------------------------------------
# STEP 35: Inspect the anatomical-site labels
# ------------------------------------------------------------
# We need to know exactly how LV is represented in the
# deposited cell-level metadata.

sort(
  unique(cell_meta$Anatomical_Site)
)


# ------------------------------------------------------------
# STEP 36: Inspect the harmonized cell-type labels
# ------------------------------------------------------------
# We expect to find:
# Ventricular_Cardiomyocytes

sort(
  unique(cell_meta$Cell_Shared_Label)
)


# ------------------------------------------------------------
# STEP 37: Inspect the data sources represented
# ------------------------------------------------------------

sort(
  unique(cell_meta$DataSource)
)


# ------------------------------------------------------------
# STEP 38: Subset to our 24 selected donors
# ------------------------------------------------------------
# This keeps all nuclei belonging to the female donors
# selected in Script 01.

target_cells <- cell_meta %>%
  dplyr::filter(
    Donor %in% target_donors
  )

dim(target_cells)


# ------------------------------------------------------------
# STEP 39: Check the number of recovered donors
# ------------------------------------------------------------

dplyr::n_distinct(
  target_cells$Donor
)


# ------------------------------------------------------------
# STEP 40: Check sex values in the selected donors
# ------------------------------------------------------------
# Because these donors were selected as female in Script 01,
# we expect only female nuclei here.

dplyr::count(
  target_cells,
  Sex
)


# ------------------------------------------------------------
# STEP 41: Check age values of the selected donors
# ------------------------------------------------------------
# This confirms that the ages in the cell-level metadata
# agree with the donor-level metadata used in Script 01.

target_cells %>%
  dplyr::distinct(
    Donor,
    Age,
    Sex,
    DataSource
  ) %>%
  dplyr::arrange(
    Age
  )


# ------------------------------------------------------------
# STEP 42: Restrict to left ventricular nuclei
# ------------------------------------------------------------
# The deposited metadata uses Anatomical_Site at the
# nucleus level.
#
# We first assume LV is coded exactly as "LV".
# STEP 35 above will confirm this.

target_lv_cells <- target_cells %>%
  dplyr::filter(
    Anatomical_Site == "LV"
  )

dim(target_lv_cells)


# ------------------------------------------------------------
# STEP 43: Count donors remaining after LV filtering
# ------------------------------------------------------------
# Expected result:
# 24 donors should still be represented because our
# primary cohort was defined using donors with LV tissue.

dplyr::n_distinct(
  target_lv_cells$Donor
)


# ------------------------------------------------------------
# STEP 44: Restrict to ventricular cardiomyocytes
# ------------------------------------------------------------
# This is our primary cell type of interest.

female_lv_vcm <- target_lv_cells %>%
  dplyr::filter(
    Cell_Shared_Label == "Ventricular_Cardiomyocytes"
  )

dim(female_lv_vcm)


# ------------------------------------------------------------
# STEP 45: Count donors represented among ventricular CMs
# ------------------------------------------------------------
# This is an important checkpoint.
#
# A donor may technically have LV tissue but could have
# very few or zero ventricular cardiomyocyte nuclei.

dplyr::n_distinct(
  female_lv_vcm$Donor
)


# ------------------------------------------------------------
# STEP 46: Count ventricular cardiomyocyte nuclei per donor
# ------------------------------------------------------------
# This is one of the most important QC tables before
# downloading/processing the count matrix.

vcm_counts_per_donor <- female_lv_vcm %>%
  dplyr::count(
    Donor,
    Age,
    DataSource,
    name = "n_vcm_nuclei"
  ) %>%
  dplyr::arrange(
    Age
  )

vcm_counts_per_donor


# ------------------------------------------------------------
# STEP 47: Add our age-group labels from Script 01
# ------------------------------------------------------------
# The cell-level metadata contains continuous age but not
# our custom younger/older grouping.
#
# We therefore join the age-group assignment from female_lv.

vcm_counts_per_donor <- vcm_counts_per_donor %>%
  dplyr::left_join(
    female_lv %>%
      dplyr::select(
        donor,
        age_group
      ),
    by = c("Donor" = "donor")
  )

vcm_counts_per_donor


# ------------------------------------------------------------
# STEP 48: Check donor numbers by age group
# ------------------------------------------------------------

vcm_counts_per_donor %>%
  dplyr::count(
    age_group,
    name = "n_donors"
  )


# ------------------------------------------------------------
# STEP 49: Summarize ventricular CM nuclei by age group
# ------------------------------------------------------------
# This gives us an early indication of whether one age group
# contributes disproportionately more nuclei than the other.

vcm_counts_per_donor %>%
  dplyr::group_by(
    age_group
  ) %>%
  dplyr::summarise(
    n_donors = dplyr::n(),
    total_vcm_nuclei = sum(n_vcm_nuclei),
    median_vcm_nuclei = median(n_vcm_nuclei),
    min_vcm_nuclei = min(n_vcm_nuclei),
    max_vcm_nuclei = max(n_vcm_nuclei),
    .groups = "drop"
  )


# ------------------------------------------------------------
# STEP 50: Save the per-donor ventricular CM count table
# ------------------------------------------------------------

readr::write_csv(
  vcm_counts_per_donor,
  "results/tables/female_LV_VCM_nuclei_per_donor.csv"
)

# Archived interactive checkpoint
sum(donor_match_table$present_in_cell_meta)

sort(unique(cell_meta$Anatomical_Site))

sort(unique(cell_meta$Cell_Shared_Label))

vcm_counts_per_donor
# Archived interactive checkpoint

print(
  vcm_counts_per_donor,
  n = Inf
)
# Archived interactive checkpoint
vcm_counts_per_donor %>%
  dplyr::group_by(age_group) %>%
  dplyr::summarise(
    n_donors = dplyr::n(),
    total_vcm_nuclei = sum(n_vcm_nuclei),
    median_vcm_nuclei = median(n_vcm_nuclei),
    min_vcm_nuclei = min(n_vcm_nuclei),
    max_vcm_nuclei = max(n_vcm_nuclei),
    .groups = "drop"
  )
# ------------------------------------------------------------
# STEP 51: Identify the exact target nuclei
# ------------------------------------------------------------
# We now create a logical filter for nuclei that satisfy all
# of our primary-analysis criteria:
#
# 1. Donor is one of our 24 selected female donors
# 2. Anatomical site is LV
# 3. Cell type is Ventricular_Cardiomyocytes

target_cell_filter <- (
  cell_meta$Donor %in% target_donors &
    cell_meta$Anatomical_Site == "LV" &
    cell_meta$Cell_Shared_Label == "Ventricular_Cardiomyocytes"
)


# ------------------------------------------------------------
# STEP 52: Count the target nuclei
# ------------------------------------------------------------
# Expected result:
# 72,104 nuclei

sum(target_cell_filter)


# ------------------------------------------------------------
# STEP 53: Store the matrix-column positions
# ------------------------------------------------------------
# The rows of cell_meta correspond to cells/nuclei.
#
# These numeric positions will later tell us which columns
# of the expression matrix belong to our target population.

target_cell_indices <- which(target_cell_filter)

length(target_cell_indices)


# ------------------------------------------------------------
# STEP 54: Inspect the first and last target indices
# ------------------------------------------------------------

head(target_cell_indices)

tail(target_cell_indices)


# ------------------------------------------------------------
# STEP 55: Create metadata for only our target nuclei
# ------------------------------------------------------------

target_cell_meta <- cell_meta[
  target_cell_indices,
]

dim(target_cell_meta)


# ------------------------------------------------------------
# STEP 56: Confirm that all 24 donors remain
# ------------------------------------------------------------

dplyr::n_distinct(
  target_cell_meta$Donor
)


# ------------------------------------------------------------
# STEP 57: Confirm all retained nuclei are LV
# ------------------------------------------------------------

unique(
  target_cell_meta$Anatomical_Site
)


# ------------------------------------------------------------
# STEP 58: Confirm all retained nuclei are ventricular CMs
# ------------------------------------------------------------

unique(
  target_cell_meta$Cell_Shared_Label
)


# ------------------------------------------------------------
# STEP 59: Save the target matrix-column indices
# ------------------------------------------------------------
# We save these positions so we do not have to calculate
# them again later.

readr::write_csv(
  tibble::tibble(
    column_index = target_cell_indices
  ),
  "results/tables/female_LV_VCM_matrix_column_indices.csv"
)


# ------------------------------------------------------------
# STEP 60: Save the target-cell metadata
# ------------------------------------------------------------

readr::write_csv(
  target_cell_meta,
  "results/tables/female_LV_VCM_cell_metadata.csv"
)


# ------------------------------------------------------------
# STEP 61: Confirm the downloaded count matrix exists
# ------------------------------------------------------------
# This is the large ~15 GB Matrix Market text file.
#
# IMPORTANT:
# We are only checking it here.
# We are NOT loading the whole file into memory.

count_file <- file.path("data_raw", "multi_study_snRNA_Seq_counts_mm_file.txt")

file.exists(count_file)


# ------------------------------------------------------------
# STEP 62: Check the count-matrix file size
# ------------------------------------------------------------
# The result should be approximately 15 GB.

file.info(count_file)$size / 1024^3


# ------------------------------------------------------------
# STEP 63: Inspect only the beginning of the count file
# ------------------------------------------------------------
# readLines(..., n = 10) reads only the first 10 lines.
#
# This is safe even though the complete file is ~15 GB.
#
# Matrix Market files usually contain:
# 1. A MatrixMarket header
# 2. Optional comment lines
# 3. Matrix dimensions
# 4. Sparse count entries

matrix_header <- readLines(
  count_file,
  n = 10
)

matrix_header


# ------------------------------------------------------------
# STEP 64: Load the gene metadata
# ------------------------------------------------------------
# This file describes the genes corresponding to the
# expression matrix.

gene_meta <- readr::read_csv(
  file.path("data_raw", "multi_study_snRNA_Seq_gene_data.csv"),
  show_col_types = FALSE
)

  
# ------------------------------------------------------------
# STEP 65: Inspect the gene metadata
# ------------------------------------------------------------

dim(gene_meta)

names(gene_meta)

head(gene_meta)


# ------------------------------------------------------------
# STEP 66: Compare metadata dimensions
# ------------------------------------------------------------
# Number of genes:

nrow(gene_meta)

# Number of nuclei in the complete dataset:

nrow(cell_meta)

# Number of nuclei needed for our analysis:

nrow(target_cell_meta)

file.exists(count_file)

file.info(count_file)$size / 1024^3

matrix_header <- readLines(
  count_file,
  n = 10
)

matrix_header

dim(gene_meta)
# ------------------------------------------------------------
# STEP 67: Final confirmation of matrix dimensions
# ------------------------------------------------------------
# From the Matrix Market header:
#
# 17,726 rows     = genes
# 1,080,773 cols  = nuclei
# 1,127,260,092   = non-zero count entries
#
# These dimensions agree exactly with:
#
# gene_meta = 17,726 genes
# cell_meta = 1,080,773 nuclei

nrow(gene_meta)

nrow(cell_meta)

length(target_cell_indices)

# ------------------------------------------------------------
# STEP 68: Save target matrix-column numbers
# ------------------------------------------------------------
# Each number identifies one column of the full count matrix
# corresponding to one of our selected LV ventricular
# cardiomyocyte nuclei.
#
# IMPORTANT:
# We preserve the ORIGINAL row order of cell_meta.
# We must never renumber or sort these indices before extraction.

writeLines(
  as.character(target_cell_indices),
  "results/tables/female_LV_VCM_matrix_columns.txt"
)

#confirm it 
length(
  readLines(
    "results/tables/female_LV_VCM_matrix_columns.txt"
  )
)

# ------------------------------------------------------------
# STEP 69: Check whether Python is available
# ------------------------------------------------------------

Sys.which(
  c(
    "python",
    "python3",
    "py"
  )
)

# ------------------------------------------------------------
# STEP 70: Verify that Python actually works
# ------------------------------------------------------------

system2(
  "python",
  "--version",
  stdout = TRUE,
  stderr = TRUE
)
system2(
  "python3",
  "--version",
  stdout = TRUE,
  stderr = TRUE
)

# ------------------------------------------------------------
# STEP 71: Confirm target-column file before extraction
# ------------------------------------------------------------

target_index_file <- "results/tables/female_LV_VCM_matrix_columns.txt"

file.exists(target_index_file)

length(
  readLines(target_index_file)
)

#73

file.exists(
  "multi_study_snRNA_Seq_counts_mm_file.txt"
)

file.exists(
  "data/multi_study_snRNA_Seq_counts_mm_file.txt"
)

#74
system2(
  "python3",
  c("-u", file.path("scripts", "extract_female_LV_VCM.py"))
)

# ------------------------------------------------------------
# STEP 75: Define the reduced count-matrix path
# ------------------------------------------------------------
# This is the subset created by the Python extraction script.
#
# It contains ONLY:
# - our 24 female donors
# - LV nuclei
# - Ventricular_Cardiomyocytes

subset_count_file <- "data/female_LV_VCM_counts.mtx"


# ------------------------------------------------------------
# STEP 76: Confirm that the reduced matrix exists
# ------------------------------------------------------------

file.exists(subset_count_file)


# ------------------------------------------------------------
# STEP 77: Check the reduced matrix size
# ------------------------------------------------------------

file.info(subset_count_file)$size / 1024^3


# ------------------------------------------------------------
# STEP 78: Inspect only the reduced Matrix Market header
# ------------------------------------------------------------
# We again read only a few lines.
# This does NOT load the 1.61 GB matrix.

subset_matrix_header <- readLines(
  subset_count_file,
  n = 10
)

subset_matrix_header

# ------------------------------------------------------------
# STEP 79: Confirm all dimensions agree
# ------------------------------------------------------------

nrow(gene_meta)
# Expected: 17726

nrow(target_cell_meta)
# Expected: 72104

length(target_cell_indices)
# Expected: 72104

# ------------------------------------------------------------
# STEP 80: Load the reduced raw-count matrix
# ------------------------------------------------------------
# Matrix::readMM() reads the Matrix Market file as a sparse
# matrix, so we do NOT create a dense 17,726 x 72,104 matrix.
#
# This may still take some time because there are more than
# 122 million non-zero entries.

library(Matrix)

vcm_counts <- Matrix::readMM(
  subset_count_file
)

# ------------------------------------------------------------
# STEP 81: Inspect the loaded sparse matrix
# ------------------------------------------------------------

class(vcm_counts)

dim(vcm_counts)

object.size(vcm_counts) / 1024^3

# Critical matching check
stopifnot(
  nrow(vcm_counts) == nrow(gene_meta)
)

stopifnot(
  ncol(vcm_counts) == nrow(target_cell_meta)
)

cat(
  "SUCCESS: count matrix dimensions match gene and cell metadata.\n"
)

# ------------------------------------------------------------
# STEP 83: Inspect the gene metadata column
# ------------------------------------------------------------

names(gene_meta)

head(gene_meta, 20)

tail(gene_meta, 20)

# ------------------------------------------------------------
# STEP 84: Check whether gene identifiers are unique
# ------------------------------------------------------------

gene_ids <- gene_meta[[1]]

length(gene_ids)

dplyr::n_distinct(gene_ids)

sum(is.na(gene_ids))

sum(duplicated(gene_ids))

names(gene_meta)
head(gene_meta, 20)
dplyr::n_distinct(gene_meta[[1]])
sum(duplicated(gene_meta[[1]]))

# ------------------------------------------------------------
# STEP 85: Identify the duplicated gene symbol
# ------------------------------------------------------------

duplicated_gene <- gene_ids[
  duplicated(gene_ids)
]

duplicated_gene


# Show every row carrying that symbol
library(tidyverse)
gene_meta %>%
  dplyr::mutate(
    gene_row = dplyr::row_number()
  ) %>%
  dplyr::filter(
    gene_short_name %in% duplicated_gene
  )
# ------------------------------------------------------------
# STEP 86: Create unique gene identifiers
# ------------------------------------------------------------
# The gene symbol TMSB15B occurs twice:
#
# row  9,803
# row 17,508
#
# We will preserve BOTH rows.
#
# make.unique() changes only the duplicated name so that
# every matrix row has a unique identifier.
#
# For example:
#
# TMSB15B
# TMSB15B.1
#
# The original biological symbol remains available in
# gene_short_name.

gene_meta <- gene_meta %>%
  dplyr::mutate(
    gene_id_unique = make.unique(gene_short_name)
  )


# ------------------------------------------------------------
# STEP 87: Verify that all computational gene IDs are unique
# ------------------------------------------------------------

length(gene_meta$gene_id_unique)

dplyr::n_distinct(
  gene_meta$gene_id_unique
)

sum(
  duplicated(gene_meta$gene_id_unique)
)


# Specifically inspect TMSB15B

gene_meta %>%
  dplyr::mutate(
    gene_row = dplyr::row_number()
  ) %>%
  dplyr::filter(
    gene_short_name == "TMSB15B"
  )
# ------------------------------------------------------------
# STEP 88: Attach unique gene IDs to the count matrix
# ------------------------------------------------------------

rownames(vcm_counts) <- gene_meta$gene_id_unique


# Confirm perfect correspondence

identical(
  rownames(vcm_counts),
  gene_meta$gene_id_unique
)
# ------------------------------------------------------------
# STEP 89: Create donor factor
# ------------------------------------------------------------
# Each of the 72,104 nuclei is assigned to one of the
# 24 biological donors.
#
# We explicitly use target_donors as the level order so
# that the final pseudobulk columns have a controlled,
# reproducible donor order.

donor_factor <- factor(
  target_cell_meta$Donor,
  levels = target_donors
)


# Confirm 24 donors

nlevels(donor_factor)

table(donor_factor)
# ------------------------------------------------------------
# STEP 90: Create sparse cell-to-donor design matrix
# ------------------------------------------------------------
#
# Rows    = 72,104 nuclei
# Columns = 24 donors

donor_design <- Matrix::sparse.model.matrix(
  ~ 0 + donor_factor
)

colnames(donor_design) <- levels(donor_factor)

dim(donor_design)
# ------------------------------------------------------------
# STEP 91: Aggregate raw counts to donor-level pseudobulk
# ------------------------------------------------------------
#
# 17,726 genes x 72,104 nuclei
#
# multiplied by
#
# 72,104 nuclei x 24 donors
#
# gives
#
# 17,726 genes x 24 donor pseudobulk samples.

pb_counts <- vcm_counts %*% donor_design
# ------------------------------------------------------------
# STEP 92: Verify pseudobulk dimensions
# ------------------------------------------------------------

dim(pb_counts)

class(pb_counts)

colnames(pb_counts)

# ------------------------------------------------------------
# STEP 93: Verify that pseudobulk aggregation did not
#          lose or duplicate any raw counts
# ------------------------------------------------------------

total_counts_cells <- sum(vcm_counts)

total_counts_pseudobulk <- sum(pb_counts)

total_counts_cells

total_counts_pseudobulk

all.equal(
  as.numeric(total_counts_cells),
  as.numeric(total_counts_pseudobulk)
)
# ------------------------------------------------------------
# STEP 94: Build donor-level metadata for pseudobulk samples
# ------------------------------------------------------------
# pb_counts has one column per donor.
#
# We now construct one metadata row per donor in exactly the
# same order as the columns of pb_counts.

pb_meta <- female_lv %>%
  dplyr::filter(
    donor %in% colnames(pb_counts)
  ) %>%
  dplyr::slice(
    match(
      colnames(pb_counts),
      donor
    )
  )


# ------------------------------------------------------------
# STEP 95: Confirm donor order matches pseudobulk columns
# ------------------------------------------------------------

identical(
  pb_meta$donor,
  colnames(pb_counts)
)
# ------------------------------------------------------------
# STEP 96: Inspect pseudobulk donor metadata
# ------------------------------------------------------------

dim(pb_meta)

pb_meta %>%
  dplyr::select(
    donor,
    age,
    age_group,
    data_source,
    sites_sampled
  )
# ------------------------------------------------------------
# STEP 97: Add VCM nuclei counts to donor metadata
# ------------------------------------------------------------

pb_meta <- pb_meta %>%
  dplyr::left_join(
    vcm_counts_per_donor %>%
      dplyr::select(
        Donor,
        n_vcm_nuclei
      ),
    by = c("donor" = "Donor")
  )


# Confirm there are no missing nuclei counts

sum(
  is.na(pb_meta$n_vcm_nuclei)
)

# ------------------------------------------------------------
# STEP 98: Calculate donor-level pseudobulk QC metrics
# ------------------------------------------------------------
# library_size:
# total raw UMI counts contributed by each donor
#
# detected_genes:
# number of genes with at least one count in that donor

pb_meta$library_size <- Matrix::colSums(
  pb_counts
)

pb_meta$detected_genes <- Matrix::colSums(
  pb_counts > 0
)
# ------------------------------------------------------------
# STEP 99: Inspect pseudobulk QC table
# ------------------------------------------------------------

pb_meta %>%
  dplyr::select(
    donor,
    age,
    age_group,
    data_source,
    n_vcm_nuclei,
    library_size,
    detected_genes
  ) %>%
  dplyr::arrange(
    n_vcm_nuclei
  ) %>%
  print(
    n = Inf
  )
# ------------------------------------------------------------
# STEP 100: Summarize pseudobulk QC by age group
# ------------------------------------------------------------

pb_meta %>%
  dplyr::group_by(
    age_group
  ) %>%
  dplyr::summarise(
    n_donors = dplyr::n(),
    median_nuclei = median(n_vcm_nuclei),
    min_nuclei = min(n_vcm_nuclei),
    max_nuclei = max(n_vcm_nuclei),
    median_library_size = median(library_size),
    min_library_size = min(library_size),
    max_library_size = max(library_size),
    median_detected_genes = median(detected_genes),
    min_detected_genes = min(detected_genes),
    max_detected_genes = max(detected_genes),
    .groups = "drop"
  )
# ------------------------------------------------------------
# STEP 101: Save pseudobulk donor QC table
# ------------------------------------------------------------

readr::write_csv(
  pb_meta,
  "results/tables/female_LV_VCM_pseudobulk_QC.csv"
)

# ------------------------------------------------------------
# STEP 102: Add counts-per-nucleus as a QC metric
# ------------------------------------------------------------
# This helps distinguish:
#
# - donors with few nuclei but reasonable sequencing depth
# - donors whose nuclei collectively have unusually low counts
#
# We are NOT using this as an automatic exclusion criterion.

pb_meta <- pb_meta %>%
  dplyr::mutate(
    counts_per_nucleus = library_size / n_vcm_nuclei
  )


# ------------------------------------------------------------
# STEP 103: Print the COMPLETE QC table
# ------------------------------------------------------------
# width = Inf prevents the detected_genes column from being
# hidden by tibble's console-width formatting.

pb_meta %>%
  dplyr::select(
    donor,
    age,
    age_group,
    data_source,
    n_vcm_nuclei,
    library_size,
    counts_per_nucleus,
    detected_genes
  ) %>%
  dplyr::arrange(
    library_size
  ) %>%
  print(
    n = Inf,
    width = Inf
  )

# ------------------------------------------------------------
# STEP 104: Summarize pseudobulk QC by original study
# ------------------------------------------------------------

pb_meta %>%
  dplyr::group_by(
    data_source
  ) %>%
  dplyr::summarise(
    n_donors = dplyr::n(),
    
    median_nuclei = median(n_vcm_nuclei),
    min_nuclei = min(n_vcm_nuclei),
    max_nuclei = max(n_vcm_nuclei),
    
    median_library_size = median(library_size),
    min_library_size = min(library_size),
    max_library_size = max(library_size),
    
    median_counts_per_nucleus = median(counts_per_nucleus),
    
    median_detected_genes = median(detected_genes),
    min_detected_genes = min(detected_genes),
    max_detected_genes = max(detected_genes),
    
    .groups = "drop"
  )
#-------------------------------------------
#Steps 1–93   → data preparation + 72,104 VCM nuclei + pseudobulk construction
#Steps 94–104 → donor metadata + preliminary pseudobulk QC


